# Generated by Django 5.2.17 on 2026-09-21 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_creditbalance_credittransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Set for manual_adjustment rows — who in the admin console made the change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
