# Generated by Django 5.2.17 on 2026-09-15 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='action',
            field=models.CharField(choices=[('invite_sent', 'Invite sent'), ('invite_revoked', 'Invite revoked'), ('invite_resent', 'Invite resent'), ('member_joined', 'Member joined'), ('role_changed', 'Role changed'), ('member_removed', 'Member removed'), ('workspace_updated', 'Workspace settings updated'), ('deletion_requested', 'Account deletion requested by owner')], max_length=30),
        ),
        migrations.AddField(
            model_name='workspace',
            name='lifecycle_status',
            field=models.CharField(
                choices=[('active', 'Active'), ('owner_deleted', 'Deleted by owner (pending permanent removal)')],
                default='active',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='workspace',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='deletion_requested_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
