# Generated by Django 5.2.17 on 2026-09-21 14:07

import apps.workspaces.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_workspace_lifecycle_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='workspace_logos/', validators=[apps.workspaces.validators.validate_logo_file_size]),
        ),
    ]
