# Generated by Django 5.2.17 on 2026-08-18 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('submitted_url', models.URLField(max_length=2048)),
                ('canonical_url', models.URLField(blank=True, max_length=2048)),
                ('normalized_host', models.CharField(max_length=255)),
                ('website_type', models.CharField(choices=[('prospect', 'Prospect'), ('client', 'Client'), ('internal', 'Internal'), ('competitor', 'Competitor')], default='prospect', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='active', max_length=20)),
                ('monitoring_frequency', models.CharField(choices=[('none', 'Not monitored'), ('monthly', 'Monthly')], default='none', max_length=10)),
                ('max_pages', models.PositiveIntegerField(default=25)),
                ('max_depth', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scans.scan')),
                ('tracks_competitor_for', models.ForeignKey(blank=True, help_text='Set only for competitor entries — the prospect/client website this competes with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='websites.website')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'normalized_host'), name='unique_workspace_host'), models.CheckConstraint(condition=models.Q(('max_pages__gte', 1), ('max_pages__lte', 500)), name='max_pages_bounded'), models.CheckConstraint(condition=models.Q(('max_depth__gte', 1), ('max_depth__lte', 10)), name='max_depth_bounded')],
            },
        ),
    ]
