# Generated by Django 5.2.17 on 2026-08-18 19:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FindingOccurrence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_key', models.CharField(max_length=100)),
                ('fingerprint', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('seo', 'SEO'), ('content', 'Content'), ('conversion', 'Conversion'), ('accessibility', 'Accessibility'), ('security_trust', 'Security/Trust'), ('competitive', 'Competitive')], max_length=20)),
                ('current_severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('business_impact', models.CharField(blank=True, max_length=100)),
                ('affected_scope', models.CharField(help_text='The specific URL, or a site-wide pattern label, this issue applies to.', max_length=2048)),
                ('recommendation', models.TextField(blank=True)),
                ('estimated_effort', models.CharField(blank=True, max_length=20)),
                ('priority_class', models.CharField(blank=True, choices=[('immediate_risk', 'Immediate Risk'), ('quick_win', 'Quick Win'), ('growth_improvement', 'Growth Improvement'), ('strategic_renovation', 'Strategic Renovation')], max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], default='open', max_length=20)),
                ('ignored_reason', models.TextField(blank=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
    ]
