# Generated by Django 5.2.17 on 2026-08-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('findings', '0001_initial'),
        ('scans', '0001_initial'),
        ('websites', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='findingoccurrence',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='scans.scanpage'),
        ),
        migrations.AddField(
            model_name='findingoccurrence',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='issue',
            name='first_seen_scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='issue',
            name='last_seen_scan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='issue',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='websites.website'),
        ),
        migrations.AddField(
            model_name='issue',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='findingoccurrence',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='findings.issue'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['website', 'status'], name='findings_is_website_d60798_idx'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('website', 'fingerprint'), name='unique_website_fingerprint'),
        ),
        migrations.AddIndex(
            model_name='findingoccurrence',
            index=models.Index(fields=['scan'], name='findings_fi_scan_id_88eb17_idx'),
        ),
    ]
