# Generated by Django 5.2.17 on 2026-08-18 19:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destination_url', models.TextField()),
                ('normalized_destination_url', models.CharField(blank=True, max_length=2048)),
                ('link_type', models.CharField(choices=[('internal', 'Internal'), ('external', 'External'), ('mailto', 'Mailto'), ('telephone', 'Telephone'), ('fragment', 'Fragment'), ('asset', 'Asset')], max_length=20)),
                ('anchor_text', models.CharField(blank=True, max_length=1024)),
                ('rel_value', models.CharField(blank=True, max_length=255)),
                ('is_nofollow', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_url', models.URLField(max_length=2048)),
                ('normalized_url', models.CharField(max_length=2048)),
                ('final_url', models.URLField(blank=True, max_length=2048)),
                ('parent_url', models.URLField(blank=True, max_length=2048)),
                ('crawl_depth', models.PositiveIntegerField(default=0)),
                ('fetch_status', models.CharField(choices=[('pending', 'Pending'), ('fetching', 'Fetching'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('http_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('response_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('redirect_count', models.PositiveIntegerField(default=0)),
                ('redirect_chain', models.JSONField(blank=True, default=list)),
                ('page_title', models.CharField(blank=True, max_length=1024)),
                ('meta_description', models.TextField(blank=True)),
                ('canonical_url', models.URLField(blank=True, max_length=2048)),
                ('robots_directives', models.CharField(blank=True, max_length=255)),
                ('h1_count', models.PositiveIntegerField(default=0)),
                ('h2_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('internal_link_count', models.PositiveIntegerField(default=0)),
                ('external_link_count', models.PositiveIntegerField(default=0)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('images_without_alt_count', models.PositiveIntegerField(default=0)),
                ('has_viewport', models.BooleanField(default=False)),
                ('has_mixed_content', models.BooleanField(default=False)),
                ('is_indexable', models.BooleanField(default=True)),
                ('has_phone_link', models.BooleanField(default=False)),
                ('has_contact_form', models.BooleanField(default=False)),
                ('has_cta_link', models.BooleanField(default=False)),
                ('html_hash', models.CharField(blank=True, max_length=64)),
                ('text_hash', models.CharField(blank=True, max_length=64)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('crawling', 'Crawling'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with errors'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=30)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('api', 'API')], default='manual', max_length=20)),
                ('root_url', models.URLField(blank=True, max_length=2048)),
                ('max_pages', models.PositiveIntegerField()),
                ('max_depth', models.PositiveIntegerField()),
                ('pages_discovered', models.PositiveIntegerField(default=0)),
                ('pages_attempted', models.PositiveIntegerField(default=0)),
                ('pages_completed', models.PositiveIntegerField(default=0)),
                ('pages_failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('crawler_version', models.CharField(default='0.1', max_length=20)),
                ('analyzer_version', models.CharField(blank=True, max_length=20)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.TextField(blank=True)),
                ('summary_data', models.JSONField(blank=True, default=dict)),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category_scores', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
