# Generated by Django 5.2.17 on 2026-08-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scans', '0001_initial'),
        ('websites', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='websites.website'),
        ),
        migrations.AddField(
            model_name='scan',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='scanevent',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='scanpage',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='scanpage',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='websites.website'),
        ),
        migrations.AddField(
            model_name='scanpage',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace'),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='destination_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_links', to='scans.scanpage'),
        ),
        migrations.AddField(
            model_name='pagelink',
            name='source_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_links', to='scans.scanpage'),
        ),
        migrations.AddIndex(
            model_name='scanpage',
            index=models.Index(fields=['scan', 'fetch_status'], name='scans_scanp_scan_id_a0e2c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='scanpage',
            constraint=models.UniqueConstraint(fields=('scan', 'normalized_url'), name='unique_scan_normalized_url'),
        ),
    ]
