# Generated by Django 5.2.17 on 2026-08-18 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('scans', '0001_initial'),
        ('websites', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scans.scan'),
        ),
        migrations.AddField(
            model_name='notification',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='websites.website'),
        ),
        migrations.AddField(
            model_name='notification',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['website', 'is_read'], name='monitoring__website_e9c99e_idx'),
        ),
    ]
