# Generated by Django 5.2.17 on 2026-09-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('scan_completed', 'Scan completed'), ('critical_finding', 'Critical finding'), ('score_drop', 'Significant score drop'), ('new_opportunity', 'New opportunity'), ('returning_issue', 'Returning issue'), ('proposal_response', 'Proposal response'), ('credits_exhausted', 'Monitoring paused — out of credits')], max_length=30),
        ),
    ]
